[package]
name = "qubit-event-bus"
version = "0.12.0"
edition = "2024"
rust-version = "1.94"
authors = ["Haixing Hu <starfish.hu@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/qubit-ltd/rs-event-bus"
description = "A lightweight, thread-safe in-process event bus for Rust"
homepage = "https://github.com/qubit-ltd/rs-event-bus"
documentation = "https://docs.rs/qubit-event-bus"
readme = "README.md"
keywords = ["event-bus", "pubsub", "events", "thread-safe", "qubit"]
categories = ["concurrency", "asynchronous"]
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/README.zh_CN.md",
    "/CHANGELOG.md",
    "/CHANGELOG.zh_CN.md",
    "/doc/**/*.md",
    "/src/**",
    "/tests/**",
]

[lib]
name = "qubit_event_bus"
doctest = true

[features]
default = []
discovery = ["qubit-spi/inventory"]

[dependencies]
qubit-argument = { version = "0.4" }
qubit-clock = "0.13"
qubit-collections = { version = "0.2" }
qubit-executor = { version = "0.8" }
qubit-id = { version = "0.6", features = ["uuid"] }
qubit-metadata = { version = "0.6", default-features = false }
qubit-retry = { version = "0.25", features = ["worker", "async"] }
qubit-spi = "0.13"
qubit-thread-pool = "0.10"
thiserror = "^2.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)', 'cfg(loom)'] }

[dev-dependencies]
loom = "^0.7"

[[bench]]
name = "local_scale"
harness = false

[[bench]]
name = "local_threads"
harness = false
