[package]
name = "qubit-event-bus"
version = "0.6.2"
edition = "2024"
rust-version = "1.94"
authors = ["Haixing Hu <starfish.hu@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/qubit-ltd/rs-event-bus"
description = "A lightweight, thread-safe in-process event bus for Rust"
homepage = "https://github.com/qubit-ltd/rs-event-bus"
documentation = "https://docs.rs/qubit-event-bus"
readme = "README.md"
keywords = ["event-bus", "pubsub", "events", "thread-safe", "qubit"]
categories = ["concurrency", "asynchronous"]
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/README.zh_CN.md",
    "/doc/**/user_guide*.md",
    "/examples/**",
    "/src/**",
    "/tests/**",
]

[lib]
name = "qubit_event_bus"
doctest = true

[dependencies]
qubit-executor = "0.6"
qubit-metadata = { version = "0.5" }
qubit-retry = { version = "0.13" }
qubit-thread-pool = "0.8"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)'] }
