[package]
name = "qubit-event-bus"
version = "0.6.0"
edition = "2024"
rust-version = "1.94"
authors = ["Haixing Hu <starfish.hu@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/qubit-ltd/rs-event-bus"
description = "A lightweight, thread-safe in-process event bus for Rust"
homepage = "https://github.com/qubit-ltd/rs-event-bus"
documentation = "https://docs.rs/qubit-event-bus"
readme = "README.md"
keywords = ["event-bus", "pubsub", "events", "thread-safe", "qubit"]
categories = ["concurrency", "asynchronous"]
exclude = [
    "align-ci.sh",
    "ci-check.sh",
    "coverage.sh",
    "style-check.sh",
    "update-submodule.sh",
    ".github/*",
    ".llvm-cov.toml",
    ".cargo-audit.toml.example",
]

[lib]
name = "qubit_event_bus"
doctest = true

[dependencies]
qubit-executor = "0.5"
qubit-metadata = { version = "0.4" }
qubit-retry = { version = "0.12" }
qubit-thread-pool = "0.7"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)'] }
