[rs-infra-style]
source = "https://github.com/qubit-ltd/rs-infra-style.git"
revision = "5d7a0d82e0b27926a472452b36cf101418b1a219"
binary = "rs-infra-style"
package = "qubit-infra-style"

[rs-infra-verify]
source = "https://github.com/qubit-ltd/rs-infra-verify.git"
revision = "86652062f373e6e6772be9a56b5c570e5d4c9816"
binary = "rs-infra-verify"
package = "qubit-infra-verify"

[rs-infra-coverage]
source = "https://github.com/qubit-ltd/rs-infra-coverage.git"
revision = "7374ec2bbd079778d58e1dbdf0da3a5c75bbe7ad"
binary = "rs-infra-coverage"
package = "qubit-infra-coverage"

[rs-infra-pages]
source = "https://github.com/qubit-ltd/rs-infra-pages.git"
revision = "24d2a605eacb6459579956cfb8b0914dd05cbcaf"
binary = "rs-infra-pages"
package = "qubit-infra-pages"

[rs-infra-ci]
source = "https://github.com/qubit-ltd/rs-infra-ci.git"
revision = "07220658707ef3ce4a5cd26df914820d9ebf18f2"
binary = "rs-infra-ci"
package = "qubit-infra-ci"

[rs-infra-dependency]
source = "https://github.com/qubit-ltd/rs-infra-dependency.git"
revision = "545b1cc0b26377780803b0f2518ac03326c9bcab"
binary = "rs-infra-dependency"
package = "qubit-infra-dependency"
