// =============================================================================
//    Copyright (c) 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0.
// =============================================================================
//! Provider inventory modules generated by `qubit-spi`.

#[cfg(feature = "discovery")]
qubit_spi::declare_sync_provider_inventory! {
    pub mod sync_provider_inventory { spec = crate::registry::EventBusSpec; }
}

#[cfg(feature = "discovery")]
qubit_spi::declare_async_provider_inventory! {
    pub mod async_provider_inventory { spec = crate::registry::EventBusSpec; }
}
