// =============================================================================
//    Copyright (c) 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0.
// =============================================================================
//! Fuzzes bounded local delivery state transitions with generated byte input.
//!
//! The shared driver checks admission, ownership, settlement, and shutdown
//! invariants using at most 4096 input bytes and 64 operations.

#![no_main]

use libfuzzer_sys::fuzz_target;

#[path = "../../tests/local/internal/local_state_machine.rs"]
mod local_state_machine;

const MAX_INPUT_LEN: usize = 4_096;

fuzz_target!(|input: &[u8]| {
    let bounded_input = &input[..input.len().min(MAX_INPUT_LEN)];
    local_state_machine::run(bounded_input);
});
